name: RsAtPlayer
main: io.github.rothes.atplayer.bukkit.RsAtPlayer
author: Rothes
authors: [Rothes]
version: ${versionString}
version-channel: ${versionChannel}
version-number: ${versionNumber}
api-version: 1.13
depend:
  - ProtocolLib
soft-depend:
  - ViaVersion
  - PlaceholderAPI